tasks:
  - name: Setup & Run
    init: |
      pip install -r requirements.txt
      alembic upgrade head
    command: |
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

ports:
  - port: 8000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-python.python
