"""init

Revision ID: 6cc9dca5ac95
Revises: 
Create Date: 2025-11-04 14:44:44.082533

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6cc9dca5ac95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clinical_records', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('owners', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('owners', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pets', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vaccinations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vaccinations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccinations', 'updated_at')
    op.drop_column('vaccinations', 'created_at')
    op.drop_column('pets', 'updated_at')
    op.drop_column('pets', 'created_at')
    op.drop_column('owners', 'updated_at')
    op.drop_column('owners', 'created_at')
    op.drop_column('clinical_records', 'updated_at')
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'created_at')
    # ### end Alembic commands ###
